import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/components/layout/header/header";
import Footer from "@/components/layout/footer/footer";
import MessagePanel from "../components/messages/messagePanel";
import PdfViewer from "@/components/pdfViewer/pdfViewer";
import ContextMenu from "@/components/contextMenu/contextMenu";
import { ContextMenuProvider } from "@/components/contextMenu/menuComponents/contextMenuProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ContextMenuProvider>
          <ContextMenu />
          <PdfViewer />
          <Header />
          <MessagePanel />
          {children}
          <Footer />
        </ContextMenuProvider>
      </body>
    </html>
  );
}